#!/bin/sh

echo "Fred's Asset Compilation"

lessc public/fred/style.less public/css/style.css
lessc public/fred/style-app.less public/css/style-app.css
lessc public/less/custom.less public/css/custom.css

echo "Done!"